/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

cleanupOutdatedCaches();

// Handle Push Events
self.addEventListener('push', (event) => {
  console.log('[Service Worker] Push Received.');
  let payload = { title: 'New Notification', body: 'You have a new update!', icon: '/icon-192.png', data: {} };

  try {
    if (event.data) {
      payload = event.data.json();
    }
  } catch (e) {
    console.warn('[Service Worker] Push data was not JSON:', event.data?.text());
    payload.body = event.data?.text() || payload.body;
  }

  const options = {
    body: payload.body,
    icon: payload.icon || '/icon-192.png',
    badge: '/badge-72.png',
    vibrate: [100, 50, 100],
    data: payload.data || {},
    actions: [
      { action: 'open', title: 'Open App' }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(payload.title, options)
  );
});

// Handle Notification Clicks
self.addEventListener('notificationclick', (event) => {
  console.log('[Service Worker] Notification click Received.');
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window open and focus it
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// Handle Background Sync
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'chat-sync') {
    console.log('[Service Worker] Background Sync Triggered!');
    event.waitUntil(
      self.clients.matchAll({ type: 'window' }).then((clients) => {
        if (clients.length > 0) {
          // Tell the open window (which has Supabase Auth Context) to process the queue
          clients.forEach(client => client.postMessage({ type: 'PROCESS_SYNC_QUEUE' }));
        } else {
          // If no windows are open, we'd ideally run a direct sync here.
          // However, Supabase auth requires localStorage (unavailable in SW) or an IndexedDB session sharing mechanism.
          console.warn('[Service Worker] Cannot background sync without an active client due to Auth token constraints. Will sync on next app open.');
        }
      })
    );
  }
});
